### ISSUE TITLE
cannot receive notification from Bluetooth device

### ISSUE THREAD

**Issue by sameerapip1** [CANDY-LINE/node-red-contrib-generic-ble#39]
When we try to get the notification we receive the following error. When using the same command in the NRF command it gives the data correctly.

(node:4511) UnhandledPromiseRejectionWarning: DBusError: Operation failed with ATT error: 0xff
    at _methodReturnHandlers.(anonymous function) (/home/pi/.node-red/node_modules/dbus-next/lib/bus.js:339:27)
    at handleMessage (/home/pi/.node-red/node_modules/dbus-next/lib/bus.js:98:11)
    at EventEmitter.MessageBus.conn.on (/home/pi/.node-red/node_modules/dbus-next/lib/bus.js:147:9)
    at EventEmitter.emit (events.js:198:13)
    at /home/pi/.node-red/node_modules/dbus-next/lib/connection.js:112:14
    at Socket.<anonymous> (/home/pi/.node-red/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:198:13)
    at emitReadable_ (_stream_readable.js:555:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:4511) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:4511) UnhandledPromiseRejectionWarning: DBusError: No notify session started
    at _methodReturnHandlers.(anonymous function) (/home/pi/.node-red/node_modules/dbus-next/lib/bus.js:339:27)
    at handleMessage (/home/pi/.node-red/node_modules/dbus-next/lib/bus.js:98:11)
    at EventEmitter.MessageBus.conn.on (/home/pi/.node-red/node_modules/dbus-next/lib/bus.js:147:9)
    at EventEmitter.emit (events.js:198:13)
    at /home/pi/.node-red/node_modules/dbus-next/lib/connection.js:112:14
    at Socket.<anonymous> (/home/pi/.node-red/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (events.js:198:13)
    at emitReadable_ (_stream_readable.js:555:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:4511) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)

**Comment by dbaba** [comment]
The error was thrown by BlueZ's [gatt_client.c](https://github.com/bluez/bluez/blob/master/src/gatt-client.c#L299) module, which means the issue is related to raw packet problem and out of Node-RED/Node.js process scope.
So you may want to check the connection between your BLE device and your Node-RED host device by using BlueZ CLI commands such as bluetoothctl, or other dbus CLI tools to test the packets and commands.
