### ISSUE TITLE
Unable to pull GATT Characteristics

### ISSUE THREAD

**Issue by bartstech** [CANDY-LINE/node-red-contrib-generic-ble#62]
Hi,

I'm using your BLE node to try and connect to a i-Syst BluePyro module (uses Nordic nRF52832). BTW your node has been the most clearly developed node, along with the tutorial. Bar none above the rest of the nodes in Node-Red and I've pretty much tried them all.
Everything works fine up until pulling GATT Char. Scan sees the module, pulls the MAC etc. 
It dies and then generates the below error.
If I use bluetoothctl, I'm able to see the services just fine, so I'm not sure where the problem is.

/__bledev/cbabcc493ee2 err:Error: Missing Peripheral Device
=>Error: Missing Peripheral Device
    at Peripheral.a (/home/pi/.node-red/node_modules/node-red-contrib-generic-ble/dist/generic-ble.js:217:31)
    at Object.onceWrapper (events.js:420:28)
    at Peripheral.emit (events.js:314:20)
    at PeripheralRemovableNoble.Noble.onDisconnect (/home/pi/.node-red/node_modules/@abandonware/noble/lib/noble.js:245:16)
    at BluezBindings.emit (events.js:314:20)
    at ProxyInterface.<anonymous> (/home/pi/.node-red/node_modules/node-red-contrib-generic-ble/dist/noble/lib/bluez/noble/lib/bluez/bindings.js:623:18)
    at ProxyInterface.emit (events.js:314:20)
    at EventEmitter.$listeners.<computed> (/home/pi/.node-red/node_modules/dbus-next/lib/client/proxy-interface.js:108:17)
    at EventEmitter.emit (events.js:314:20)
    at handleMessage (/home/pi/.node-red/node_modules/dbus-next/lib/bus.js:118:23)
    at EventEmitter.<anonymous> (/home/pi/.node-red/node_modules/dbus-next/lib/bus.js:147:...

**Comment by bartstech** [comment]
I retract this. All of a sudden it started working. No clue why?!
