### ISSUE TITLE
this._discoveredPeripheralUUids.indexOf is not a function

### ISSUE THREAD

**Issue by rugarci** [CANDY-LINE/node-red-contrib-generic-ble#71]
Once I have connected to a peripheral correctly, from time to time I get and error message and node-red stops

> 3 Jun 08:26:09 - [red] Uncaught Exception:
> 3 Jun 08:26:09 - [error] TypeError: this._discoveredPeripheralUUids.indexOf is not a function
>     at PeripheralRemovableNoble.onMiss (/data/node_modules/node-red-contrib-generic-ble/dist/noble/noble/index.js:61:72)
>     at BluezBindings.emit (node:events:513:28)
>     at BluezBindings.onDeviceMissed (/data/node_modules/node-red-contrib-generic-ble/dist/noble/lib/bluez/noble/lib/bluez/bindings.js:716:10)
>     at BluezBindings.onDevicesServicesCharacteristicsMissed (/data/node_modules/node-red-contrib-generic-ble/dist/noble/lib/bluez/noble/lib/bluez/bindings.js:710:12)
>     at ProxyInterface.emit (node:events:513:28)
>     at EventEmitter.$listeners.<computed> (/data/node_modules/dbus-next/lib/client/proxy-interface.js:108:17)
>     at EventEmitter.emit (node:events:513:28)
>     at handleMessage (/data/node_modules/dbus-next/lib/bus.js:118:23)
>     at EventEmitter.<anonymous> (/data/node_modules/dbus-next/lib/bus.js:147:9)
>     at EventEmitter.emit (node:events:513:28)

Running in RPI 3 with the latest versions of node-red and node-red-contrib-generic-ble

> 3 Jun 08:23:23 - [info] Node-RED version: v3.0.2
> 3 Jun 08:23:23 - [info] Node.js  version: v16.20.0
> 3 Jun 08:23:23 - [info] Linux 5.10.103-v7+ arm LE

Anyone can help? 

Thanks!

**Comment by hotrock3** [comment]
Running into the same problem on an OrangePi
latest version of Node-RED (3.0.2)
Node.js (20.3.0)
Linux 5.16.17-sun50iw6 arm64 LE

**Comment by dhruvjhalani95** [comment]
Facing the same problem. Were anyone of you able to find a solution to the problem @hotrock3 @rugarci

**Comment by GVC16** [comment]
Encountering same problem. whether it is node-red-contrib-generic-ble@4.0.3 or 4.0.1, causing node-RED service to fail.

**Comment by hotrock3** [comment]
> Facing the same problem. Were anyone of you able to find a solution to the problem @hotrock3 @rugarci

@dhruvjhalani95 No solution to this problem identified. Shifting to ESP32 and the use of MQTT instead of using ATMega328 with BLE. This is probably a better approach in the long run but I was trying to avoid buying more stuff.

**Comment by emc-vishaal** [comment]
Same issue here. RasPi 4 with latest node-red v3.0.2
node.js v18.17.1
linux 6.1.21-v8+ arm LE

Is there any other setup to connect to BLE/GATT devices using node-red?

**Comment by Switchblade2** [comment]
Same issue here on a Raspberry Pi 4 with 
Node-RED version: v4.0.8
Node.js  version: v20.18.1
Linux 6.6.62+rpt-rpi-v8 arm64 LE

**Comment by rugee-f** [comment]
I have the same issue - any idea how to solve? 
The nodes don't work under actual bookworm 64 Bit OS, but they are running smooth on a windows installation...
Node-Red is in Version 4.1.0 on both systems...
Is it possible that user rights or access rights of underlaying noble modules affect functionality?

**Comment by sneumeister** [comment]
Seems to be the same issue I discovered:
[Issue #74](https://github.com/CANDY-LINE/node-red-contrib-generic-ble/issues/74)

Try the patch at the end of the. At least no more crash here......
